      - name: Build and Publish
        run: |
          cd 08-cicd/projects/hello-app

          registry="yousifdevops"
          sha=$(git rev-parse --short HEAD)
          primary_tag="${registry}/cicd-test:${sha}"

          docker build -t $primary_tag -f Dockerfile .
          docker push $primary_tag

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" = "main" ]; then
            retention_tag="${registry}/cicd-test:rc-${sha}"
            docker tag $primary_tag $retention_tag
            docker push $retention_tag
          else
            retention_tag="${registry}/cicd-test:alpha-${sha}"
            docker tag $primary_tag $retention_tag
            docker push $retention_tag
          fi